- name: secret
  hosts: myserver
  become: yes
  vars_files:
    - mypass.txt
  tasks:
    - name: install Python MySQL Module
      command: "python3-pip install PyMySQL"
    - name: install mariadb
      yum:
        name: mariadb105-server
        state: present
    - name: starting mariadb
      service:
        name: mariadb
        state: started

    - name: login mysql
      mysql_user:
        name: "{{ username }}"
        password: "{{ password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        check_implicit_admin: yes
        update_password: always
        state: present
