---
# tasks file for php_role
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: Install PHP
  apt:
    name: php
    state: present

- name: Install PHP-FPM
  apt:
    name: php8.3-fpm
    state: present

- name: Start and enable PHP-FPM service
  service:
    name: php8.3-fpm
    state: started
    enabled: true

